import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/**
 * Analysis report download control (Req 5.5-5.7).
 *
 * Lets the User generate a structured Analysis_Report for the current analysis
 * session (Req 5.1-5.4, 5.7), choose the export format (PDF / Word), and then
 * download it. Generation drives the Agent's report-generation MCP via
 * `POST /reports/generate`; download resolves a presigned URL from
 * `GET /reports/{id}/download` and opens it to trigger a browser download
 * (Req 5.5). A missing export (backend 404) is surfaced gracefully via
 * `useNotify` (Req 12.17).
 */
import { useEffect, useState } from 'react';
import { Button, Select, Space, Typography } from 'antd';
import { DownloadOutlined, FileTextOutlined } from '@ant-design/icons';
import { useNotify } from '../../../hooks/useNotify';
import { reportsService } from '../../../services/reportsService';
import { SPACING } from '../../../theme/tokens';
const { Text } = Typography;
export function ReportDownloadControl({ analysisId, report, onReportGenerated, }) {
    const notify = useNotify();
    const [format, setFormat] = useState('pdf');
    // The report generated by this control, with download-availability flags.
    const [generated, setGenerated] = useState(null);
    const [generating, setGenerating] = useState(false);
    const [downloading, setDownloading] = useState(false);
    // Reset the locally-generated report whenever the analysis session changes.
    useEffect(() => {
        setGenerated(null);
    }, [analysisId]);
    // The report id to download: prefer the locally-generated one, else the prop.
    const reportId = generated?.id ?? report?.id ?? null;
    const hasReport = reportId != null;
    /**
     * Whether the chosen format is available for download.
     *
     * When this control generated the report we know the exact availability from
     * the `has_pdf`/`has_docx` flags. An existing report from the analysis flow
     * does not expose those flags, so we allow the attempt and surface a 404
     * gracefully.
     */
    const formatAvailable = (fmt) => {
        if (generated) {
            return fmt === 'pdf' ? generated.has_pdf : generated.has_docx;
        }
        return hasReport;
    };
    const handleGenerate = async () => {
        setGenerating(true);
        try {
            const response = await reportsService.generate(analysisId, format);
            setGenerated(response);
            onReportGenerated?.({
                id: response.id,
                title: response.title,
                content: response.content,
            });
            notify.success('分析报告已生成');
        }
        catch (err) {
            notify.error('报告生成失败', err instanceof Error ? err.message : '生成报告时出现问题，请稍后重试。');
        }
        finally {
            setGenerating(false);
        }
    };
    const handleDownload = async () => {
        if (!reportId) {
            return;
        }
        setDownloading(true);
        try {
            const response = await reportsService.getDownloadUrl(reportId, format);
            // Open the presigned URL to trigger the browser download (Req 5.5).
            window.open(response.download_url, '_blank', 'noopener,noreferrer');
            notify.success('已开始下载分析报告');
        }
        catch (err) {
            notify.error('下载失败', err instanceof Error ? err.message : '该格式的报告暂不可用，请稍后重试。');
        }
        finally {
            setDownloading(false);
        }
    };
    return (_jsxs(Space, { size: SPACING.sm, wrap: true, align: "center", children: [_jsx(Text, { strong: true, children: "\u62A5\u544A\u683C\u5F0F\uFF1A" }), _jsx(Select, { value: format, onChange: setFormat, style: { width: 120 }, "aria-label": "\u62A5\u544A\u683C\u5F0F", options: [
                    { label: 'PDF', value: 'pdf' },
                    { label: 'Word', value: 'docx' },
                ] }), _jsx(Button, { type: "primary", icon: _jsx(FileTextOutlined, {}), loading: generating, onClick: handleGenerate, children: hasReport ? '重新生成报告' : '生成报告' }), _jsx(Button, { icon: _jsx(DownloadOutlined, {}), loading: downloading, disabled: !hasReport || !formatAvailable(format), onClick: handleDownload, children: "\u4E0B\u8F7D" })] }));
}
export default ReportDownloadControl;
