/**
 * Analysis report download control (Req 5.5-5.7).
 *
 * Lets the User generate a structured Analysis_Report for the current analysis
 * session (Req 5.1-5.4, 5.7), choose the export format (PDF / Word), and then
 * download it. Generation drives the Agent's report-generation MCP via
 * `POST /reports/generate`; download resolves a presigned URL from
 * `GET /reports/{id}/download` and opens it to trigger a browser download
 * (Req 5.5). A missing export (backend 404) is surfaced gracefully via
 * `useNotify` (Req 12.17).
 */

import { useEffect, useState } from 'react';
import { Button, Select, Space, Typography } from 'antd';
import { DownloadOutlined, FileTextOutlined } from '@ant-design/icons';

import { useNotify } from '../../../hooks/useNotify';
import { reportsService } from '../../../services/reportsService';
import { SPACING } from '../../../theme/tokens';
import type { Report } from '../../../types/analysis';
import type { ReportFormat, ReportResponse } from '../../../types/reports';

const { Text } = Typography;

export interface ReportDownloadControlProps {
  /** The analysis session to generate / download a report for. */
  analysisId: string;
  /** An already-generated report from the analysis flow, if any (reused for download). */
  report?: Report | null;
  /** Notifies the parent when a new report has been generated (lifts state). */
  onReportGenerated?: (report: Report) => void;
}

export function ReportDownloadControl({
  analysisId,
  report,
  onReportGenerated,
}: ReportDownloadControlProps) {
  const notify = useNotify();
  const [format, setFormat] = useState<ReportFormat>('pdf');
  // The report generated by this control, with download-availability flags.
  const [generated, setGenerated] = useState<ReportResponse | null>(null);
  const [generating, setGenerating] = useState(false);
  const [downloading, setDownloading] = useState(false);

  // Reset the locally-generated report whenever the analysis session changes.
  useEffect(() => {
    setGenerated(null);
  }, [analysisId]);

  // The report id to download: prefer the locally-generated one, else the prop.
  const reportId = generated?.id ?? report?.id ?? null;
  const hasReport = reportId != null;

  /**
   * Whether the chosen format is available for download.
   *
   * When this control generated the report we know the exact availability from
   * the `has_pdf`/`has_docx` flags. An existing report from the analysis flow
   * does not expose those flags, so we allow the attempt and surface a 404
   * gracefully.
   */
  const formatAvailable = (fmt: ReportFormat): boolean => {
    if (generated) {
      return fmt === 'pdf' ? generated.has_pdf : generated.has_docx;
    }
    return hasReport;
  };

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const response = await reportsService.generate(analysisId, format);
      setGenerated(response);
      onReportGenerated?.({
        id: response.id,
        title: response.title,
        content: response.content,
      });
      notify.success('分析报告已生成');
    } catch (err) {
      notify.error(
        '报告生成失败',
        err instanceof Error ? err.message : '生成报告时出现问题，请稍后重试。',
      );
    } finally {
      setGenerating(false);
    }
  };

  const handleDownload = async () => {
    if (!reportId) {
      return;
    }
    setDownloading(true);
    try {
      const response = await reportsService.getDownloadUrl(reportId, format);
      // Open the presigned URL to trigger the browser download (Req 5.5).
      window.open(response.download_url, '_blank', 'noopener,noreferrer');
      notify.success('已开始下载分析报告');
    } catch (err) {
      notify.error(
        '下载失败',
        err instanceof Error ? err.message : '该格式的报告暂不可用，请稍后重试。',
      );
    } finally {
      setDownloading(false);
    }
  };

  return (
    <Space size={SPACING.sm} wrap align="center">
      <Text strong>报告格式：</Text>
      <Select<ReportFormat>
        value={format}
        onChange={setFormat}
        style={{ width: 120 }}
        aria-label="报告格式"
        options={[
          { label: 'PDF', value: 'pdf' },
          { label: 'Word', value: 'docx' },
        ]}
      />
      <Button
        type="primary"
        icon={<FileTextOutlined />}
        loading={generating}
        onClick={handleGenerate}
      >
        {hasReport ? '重新生成报告' : '生成报告'}
      </Button>
      <Button
        icon={<DownloadOutlined />}
        loading={downloading}
        disabled={!hasReport || !formatAvailable(format)}
        onClick={handleDownload}
      >
        下载
      </Button>
    </Space>
  );
}

export default ReportDownloadControl;
